version: '3'

services:

  edufund:
    image: sandy/edufund:${TAG:-1.0-dev}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - HTTP_PORT=80
      - DB_CONN=sslmode=disable host=172.17.0.4 port=5432 user=postgres dbname=edufund password=Standar123.
    ports:
      - "9011:80"